### ISSUE TITLE
TODO for 2021

### ISSUE THREAD

**Issue by adrfantini** [apazaf/gbpn#1]
- [x] update past editions pictures (in `past_editions/slider.md` and `static/img/`), see #3 
- [ ] write post with summary of last year
- [x] update details (in `details/`)
- [x] new news post (in `post/`)
- [x] new REGISTER form (in `register/`)
- [ ] check our notes from last year and update things
- [x] new home page (in `home/hero.md`)
- [x] consider cancelling due to unforeseen pandemic
- [x] do all of the above but for IT
